name: Workflow events

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        shell: bash
        run: echo "this workflow was triggered by a(n) ${{github.event_name}}"
